var wpTimeline;(function($){var extWin;wpTimeline={jsonAPIbase:'https://public-api.wordpress.com/rest/v1',hasUpgradedProxy:false,intents:[],intentsHTML:[],activeIntent:{},likeStatuses:[],reblogStatuses:[],reblogFormShowing:[],isLoggedIn:false,APIqueue:[],me:false,site:false,posts:false,blog_id:false,isJetpack:false,postsbyID:[],formatedDates:[],i18n:false,isIE:false,IEVersion:'',wpTimeline:function(){wpTimeline.query=wpTimeline.splitParams(location.hash.replace(/^#/,''));wpTimeline.isIE=(-1!=navigator.userAgent.search('MSIE'));if(wpTimeline.isIE){var IEVersion=navigator.userAgent.match(/MSIE\s?(\d+)\.?\d*;/);wpTimeline.IEVersion=parseInt(IEVersion[1]);}
wpTimeline.loadTranslation();wpTimeline.getButtonData(wpTimeline.query['blog'],function(){wpTimeline.getBatchIntentData(wpTimeline.displayWidget);});},splitParams:function(queryString){var params={};jQuery.each(queryString.split('&'),function(i,value){var pair=value.split('=');params[pair[0]]=decodeURIComponent(pair[1]);});return params;},displayWidget:function(){var hasPosts=true;if(wpTimeline.posts.found==0)
hasPosts=false;var options='';if(wpTimeline.query.show_gravatars=='true')
options+=' gravatars-on';else
options+=' gravatars-off';if('dark'==wpTimeline.query.theme)
options+=' theme-dark';if(wpTimeline.me)
wpTimeline.isLoggedIn=true;for(var i=0;i<wpTimeline.posts.posts.length;i++){wpTimeline.generateIntentsHTML(wpTimeline.posts.posts[i]);wpTimeline.postsbyID[wpTimeline.posts.posts[i].ID]=wpTimeline.posts.posts[i];wpTimeline.formatedDates[wpTimeline.posts.posts[i].ID]=wpTimeline.formatDate(wpTimeline.posts.posts[i].date);}
if(wpTimeline.followingStatus===true){var followingStatus=wpTimeline.i18n.translate('Following').fetch();var followingClass='follow-button follow-button-following';}else{var followingStatus=wpTimeline.i18n.translate('Follow').fetch();var followingClass='follow-button';}
wpTimeline.loadCSS();var template=_.template(jQuery('#timeline').html());jQuery('body').find('#target').html(template({blogTitle:wpTimeline.site.name,description:wpTimeline.site.description,blogURL:wpTimeline.site.URL,posts:wpTimeline.posts.posts,hasPosts:hasPosts,intents:wpTimeline.intentsHTML,options:options,dates:wpTimeline.formatedDates,followingStatus:followingStatus,followingClass:followingClass,noPostsMessage:wpTimeline.i18n.translate('No posts were found for this blog.').fetch()}));jQuery('.posts').css('height',wpTimeline.query['height']-(56+jQuery('.widget-footer').height()+jQuery('.widget-header').height()));jQuery('body').find('.post-content').find('a').attr('target','_parent');if(wpTimeline.query.link_color){jQuery('body').find('.post-content').find('a').css({color:wpTimeline.query.link_color});jQuery('body').find('.short-link').css({color:wpTimeline.query.link_color});}
wpTimeline.handleIntentClicks();wpTimeline.handleFollowButtonClick();if(wpTimeline.isIE&&wpTimeline.IEVersion<9)
jQuery('#follow-button').hide();},formatDate:function(isostr){var parts=isostr.match(/\d+/g);var dateobject=new Date(parts[0],parts[1]-1,parts[2],parts[3],parts[4],parts[5]);var month='';switch(dateobject.getMonth()){case 0:month=wpTimeline.i18n.translate('Jan').fetch();break;case 1:month=wpTimeline.i18n.translate('Feb').fetch();break;case 2:month=wpTimeline.i18n.translate('Mar').fetch();break;case 3:month=wpTimeline.i18n.translate('Apr').fetch();break;case 4:month=wpTimeline.i18n.translate('May').fetch();break;case 5:month=wpTimeline.i18n.translate('Jun').fetch();break;case 6:month=wpTimeline.i18n.translate('Jul').fetch();break;case 7:month=wpTimeline.i18n.translate('Aug').fetch();break;case 8:month=wpTimeline.i18n.translate('Sep').fetch();break;case 9:month=wpTimeline.i18n.translate('Oct').fetch();break;case 10:month=wpTimeline.i18n.translate('Nov').fetch();break;case 11:month=wpTimeline.i18n.translate('Dec').fetch();break;}
var year='';var d=new Date();if(d.getFullYear()!=dateobject.getFullYear())
year=" "+dateobject.getFullYear();return month+" "+dateobject.getDate()+year;},generateIntentsHTML:function(post){wpTimeline.intentsHTML[post.ID]="<div class='post-footer post-footer-"+post.ID+"'>";wpTimeline.intentsHTML[post.ID]+='<a href="'+post.short_URL+'" target="_parent" class="short-link">'+post.short_URL.replace("http://","")+'</a>';if(wpTimeline.isIE&&wpTimeline.IEVersion<9){wpTimeline.intentsHTML[post.ID]+="</div>";return;}
wpTimeline.intentsHTML[post.ID]+="<div class='post-actions intents intents-"+post.ID+"'>";for(var intent in wpTimeline.intents){wpTimeline.intentsHTML[post.ID]+="<a href='#' class='intent post-action-"+intent+"' data-post-id= '"+post.ID+"' data-intent='"+intent+"'>"+wpTimeline.intents[intent].label(post)+"</a>";}
wpTimeline.intentsHTML[post.ID]+="</div>";wpTimeline.intentsHTML[post.ID]+="</div>";},handleIntentClicks:function(){$('.intent').click(function(e){e.preventDefault();var intent=$(this).attr('data-intent');var postID=$(this).attr('data-post-id');if(wpTimeline.intents[intent]){if(true===wpTimeline.intents[intent].requiresLogin){if(wpTimeline.isLoggedIn){wpTimeline.intents[intent].onClick($(this),wpTimeline.postsbyID[postID]);return;}
wpTimeline.activeFollowButton={};wpTimeline.activeIntent={intent:intent,post:wpTimeline.postsbyID[postID],element:$(this)};wpTimeline.openLoginWindow();return;}else{wpTimeline.intents[intent].onClick($(this),wpTimeline.postsbyID[postID]);return;}}});},handleFollowButtonClick:function(){$('.follow-button').click(function(e){e.preventDefault();if(!wpTimeline.isLoggedIn){wpTimeline.activeIntent={};wpTimeline.activeFollowButton={element:$(this)};wpTimeline.openLoginWindow();return;}
wpTimeline.doFollow($(this));return;});},doFollow:function(element){if(!wpTimeline.followingStatus){wpTimeline.followBlog(function(){element.html(wpTimeline.i18n.translate('Following').fetch());wpTimeline.followingStatus=true;element.addClass('follow-button-following');});}else{wpTimeline.unFollowBlog(function(){element.html(wpTimeline.i18n.translate('Follow').fetch());wpTimeline.followingStatus=false;element.removeClass('follow-button-following');});}},handleLogin:function(event){if("undefined"==typeof event.event)
return;if('login'==event.event&&event.success){wpTimeline.isLoggedIn=true;wpTimeline.hasUpgradedProxy=false;$.wpcom_proxy_rebuild();wpTimeline.getBatchIntentData(function(){wpTimeline.intentsHTML=[];for(var i=0;i<wpTimeline.posts.posts.length;i++){wpTimeline.generateIntentsHTML(wpTimeline.posts.posts[i]);jQuery('.post-footer-'+wpTimeline.posts.posts[i].ID).html(wpTimeline.intentsHTML[wpTimeline.posts.posts[i].ID]);}
if(wpTimeline.query.link_color){jQuery('body').find('.post-content').find('a').css({color:wpTimeline.query.link_color});jQuery('body').find('.short-link').css({color:wpTimeline.query.link_color});}
wpTimeline.handleIntentClicks();if(wpTimeline.followingStatus===true){$('#follow-button').text(wpTimeline.i18n.translate('Following').fetch());$('#follow-button').addClass('follow-button-following');}
if(wpTimeline.activeIntent.intent){if('undefined'==typeof wpTimeline.likeStatuses[wpTimeline.activeIntent.post.ID]||!wpTimeline.likeStatuses[wpTimeline.activeIntent.post.ID].i_like)
wpTimeline.intents[wpTimeline.activeIntent.intent].onClick(wpTimeline.activeIntent.element,wpTimeline.activeIntent.post);wpTimeline.activeIntent={};}else if(wpTimeline.activeFollowButton.element&&!wpTimeline.followingStatus){wpTimeline.doFollow(wpTimeline.activeFollowButton.element);wpTimeline.activeFollowButton={};}
return;});}},openLoginWindow:function(){if(extWin){if(!extWin.closed){extWin.close();}
extWin=false;}
$('#wp-login-polling-iframe').remove();var url='https://wordpress.com/public.api/connect/?action=request&amp;service=wordpress';extWin=window.open(url,'likeconn','status=0,toolbar=0,location=1,menubar=0,directories=0,resizable=1,scrollbars=0,height=500,width=500');var loginIframe=$("<iframe id='wp-login-polling-iframe'></iframe>");loginIframe.attr("src","https://wordpress.com/public.api/connect/?iframe=true");loginIframe.css("display","none");$(document.body).append(loginIframe);},loadCSS:function(){var style=document.createElement('link');style.setAttribute('type','text/css');style.setAttribute('rel','stylesheet');style.setAttribute('href','../../s0.wordpress.com/i/noticons/noticons.css');jQuery(document).find('head')[0].appendChild(style);var style=document.createElement('link');style.setAttribute('type','text/css');style.setAttribute('rel','stylesheet');style.setAttribute('href','//fonts.googleapis.com/css?family=Open+Sans:400italic,700italic,400,700');jQuery(document).find('head')[0].appendChild(style);var style=document.createElement('link');style.setAttribute('type','text/css');style.setAttribute('rel','stylesheet');style.setAttribute('href','stylec81e.css?2');jQuery(document).find('head')[0].appendChild(style);},loadTranslation:function(){var lang='en';if(wpTimeline.query.lang)
lang=wpTimeline.query.lang;var load_default=true;if('en'!=lang){var json_locale_data;jQuery.ajax({url:'/languages/'+lang+'.json',dataType:'json',async:false,success:function(json){json_locale_data=json;load_default=false;}});}
if(null==json_locale_data)
load_default=true;if(load_default){var json_locale_data={"":{"domain":"messages","lang":lang,"plural-forms":"nplurals=2; plural=(n != 1);"}};}
wpTimeline.i18n=new Jed({locale_data:{"messages":json_locale_data},"domain":"messages"});},getButtonData:function(blog_url,callback){var remainingRequests=3,maybeCallback;maybeCallback=function(){if(!--remainingRequests){callback();}};wpTimeline.ajax({path:'/me',type:'GET',success:function(response){wpTimeline.me=response;maybeCallback()},error:function(){maybeCallback();}});blog_url=encodeURIComponent(blog_url);jQuery.ajax({url:wpTimeline.jsonAPIbase+'/sites/'+blog_url,success:function(response){wpTimeline.site=response;wpTimeline.blog_id=response.ID;wpTimeline.isJetpack=response.jetpack;},complete:maybeCallback,dataType:'jsonp'});jQuery.ajax({url:wpTimeline.jsonAPIbase+'/sites/'+blog_url+'/posts',success:function(response){wpTimeline.posts=response;},error:function(){wpTimeline.posts={found:0,posts:[]};},complete:maybeCallback,dataType:'jsonp'});},getBatchIntentData:function(callback){if(wpTimeline.isIE&&wpTimeline.IEVersion<9){callback();return;}
wpTimeline.APIqueue=[];wpTimeline.likeStatuses=[];wpTimeline.reblogStatuses=[];for(var i=0;i<wpTimeline.posts.posts.length;i++){wpTimeline.APIqueue.push('/sites/'+wpTimeline.blog_id+'/posts/'+wpTimeline.posts.posts[i].ID+'/likes/mine');if(!wpTimeline.isJetpack)
wpTimeline.APIqueue.push('/sites/'+wpTimeline.blog_id+'/posts/'+wpTimeline.posts.posts[i].ID+'/reblogs/mine');}
wpTimeline.APIqueue.push('/sites/'+wpTimeline.blog_id+'/follows/mine');var batchRequest={path:'/batch',type:'GET',url:'https://public-api.wordpress.com/rest/v1/batch',data:'',success:function(response){for(var path in response){if(!response[path]['error_data']&&!response[path]['errors']){var pieces=path.split('http://widgets.wp.com/');if('likes'==pieces[5])
wpTimeline.likeStatuses[pieces[4]]=response[path];else if('reblogs'==pieces[5])
wpTimeline.reblogStatuses[pieces[4]]=response[path];else if('follows'==pieces[3])
wpTimeline.followingStatus=response[path].is_following;else
continue;}}
callback();},error:function(response){console.log('batch loading error');}};var amp='';for(var i=0;i<wpTimeline.APIqueue.length;i++){if(i>0)
amp='&';batchRequest.data+=amp+'urls[]='+wpTimeline.APIqueue[i];}
wpTimeline.ajax(batchRequest);},likePost:function(post_id,success,fail){return this.ajax({type:'POST',path:'/sites/'+wpTimeline.blog_id+'/posts/'+post_id+'/likes/new',query:'source=timeline_widget',success:success,error:fail});},unlikePost:function(post_id,success,fail){return this.ajax({type:'POST',path:'/sites/'+wpTimeline.blog_id+'/posts/'+post_id+'/likes/mine/delete',success:success,error:fail});},followBlog:function(success,fail){return this.ajax({type:'POST',path:'/sites/'+wpTimeline.blog_id+'/follows/new',success:success,error:fail});},unFollowBlog:function(success,fail){return this.ajax({type:'POST',path:'/sites/'+wpTimeline.blog_id+'/follows/mine/delete',success:success,error:fail});},reblogPost:function(blog_id,post_id,note,success,fail){return this.ajax({type:'POST',path:'/sites/'+blog_id+'/posts/'+post_id+'/reblogs/new',success:success,error:fail,data:{note:note}});},getSiteInfo:function(blog_id,success,fail){return this.ajax({type:'GET',path:'/sites/'+blog_id,success:success,error:fail});},ajax:function(options){var request={path:options.path,method:options.type,url:wpTimeline.jsonAPIbase+options.path};if(options.type.toLowerCase()=='post'){request.body=options.data;request.query=options.query;}else{request.query=options.data;}
var data={event:'ajax',request:request};if(wpTimeline.isIE&&wpTimeline.IEVersion<9){jQuery.support.cors=true;return jQuery.ajax({type:options.type+'?callback=?',url:request.url,crossDomain:true,dataType:"jsonp",data:options.data,success:function(response){options.success(response,request.path)},error:function(response){options.error(response,request.path)}});}
var makeProxyCall=function(){return jQuery.wpcom_proxy_request(request,function(response,statusCode){if(200==statusCode)
'function'==typeof options.success&&options.success(response,request.path);else
'function'==typeof options.error&&options.error(statusCode,request.path);});};if(wpTimeline.hasUpgradedProxy){return makeProxyCall();}else{return jQuery.wpcom_proxy_request({metaAPI:{accessAllUsersBlogs:true}}).done(function(){wpTimeline.hasUpgradedProxy=true;makeProxyCall();});}}};wpTimeline.intents['like']={requiresLogin:true,label:function(post){if('undefined'!=typeof wpTimeline.likeStatuses[post.ID]&&wpTimeline.likeStatuses[post.ID].i_like){return wpTimeline.i18n.translate('Liked').fetch();}else{return wpTimeline.i18n.translate('Like').fetch();}},onClick:function(element,post){var likeStatus=wpTimeline.likeStatuses[post.ID];if(!likeStatus.i_like){wpTimeline.likePost(post.ID,function(){element.html(wpTimeline.i18n.translate('Liked').fetch());wpTimeline.likeStatuses[post.ID].i_like=true;});}else{wpTimeline.unlikePost(post.ID,function(){element.html(wpTimeline.i18n.translate('Like').fetch());wpTimeline.likeStatuses[post.ID].i_like=false;});}}};})(jQuery);jQuery(document).ready(function($){wpTimeline.wpTimeline();pm.bind('loginMessage',function(e){wpTimeline.handleLogin(e);});});